### ISSUE TITLE
This site can't be reached

### ISSUE THREAD

**Issue by tipoc123** [nedap/exonum-block-explorer#2]
```
root@horizontalvol:~/exonum/exonum-block-explorer# npm start

> exonum-block-explorer@0.0.1 start /root/exonum/exonum-block-explorer
> webpack-dev-server

Project is running at http://localhost:8080/
webpack output is served from /

ts-loader: Using typescript@2.5.3 and /root/exonum/exonum-block-explorer/tsconfig.json
Hash: af70828f749354eb8b36
Version: webpack 2.7.0
Time: 21209ms
                                     Asset     Size  Chunks                    Chunk Names
./img/d087ee0e81e19237df4195ad2f012fc9.png  31.4 kB          [emitted]         
./img/6d8b58bec45a4ee344703df6edb1512a.png  71.6 kB          [emitted]         
./img/3b35be9d690e2cd34742dd0f9094b1db.png  56.8 kB          [emitted]         
./img/251ba19534de3eec2e262293aa57682f.png    25 kB          [emitted]         
./img/efc239cd23ca7b3c0caf2eb919ad0f7d.gif  43.3 kB          [emitted]         
                                  index.js  3.57 MB       0  [emitted]  [big]  app
chunk    {0} index.js (app) 1.34 MB [entry] [rendered]
    [1] ./~/vue/dist/vue.js 279 kB {0} [built]
   [22] ./src/index.ts 599 bytes {0} [built]
   [23] (webpack)-dev-server/client?http://localhost:8080 7.95 kB {0} [built]
   [53] ./~/loglevel/lib/loglevel.js 7.86 kB {0} [built]
   [60] ./~/strip-ansi/index.js 161 bytes {0} [built]
   [71] ./src/router.ts 890 bytes {0} [built]
   [72] ./src/store.ts 31 bytes {0} [built]
   [74] ./~/url/url.js 23.3 kB {0} [built]
   [76] ./src/components/Navigation.vue 1.85 kB {0} [built]
   [95] ./~/vuetify/dist/vuetify.js 507 kB {0} [built]
   [97] (webpack)-dev-server/client/overlay.js 3.73 kB {0} [built]
   [98] (webpack)-dev-server/client/socket.js 1.05 kB {0} [built]
  [100] (webpack)/hot nonrecursive ^\.\/log$ 160 bytes {0} [built]
  [101] (webpack)/hot/emitter.js 77 bytes {0} [built]
  [102] multi (webpack)-dev-server/client?http://localhost:8080 ./src/index.ts 40 bytes {0} [built]
     + 88 hidden modules
webpack: Compiled successfully.

```

I successfully started blockchain explorer. Then type http://x.x.x.x:8080/ (i.e. server ip, not localhost:8080) in browser and nothing happened (Chrome shows ERR_CONNECTION_REFUSED). Tried with both CORS enabled and disabled.

**Comment by vnermolaev** [comment]
Clarify me something.
Do you run the blockchain app and the explorer on different hosts or the same one?

Try to execute on the blockchain host and some other host if possible
```
curl http://your-blockchain-host:port/api/explorer/v1/blocks?count=10
```
The default port is 8000. You'll have to update it if you have a custom config.
Do you get any blocks?

**Comment by tipoc123** [comment]
I have executed curl http://your-blockchain-host:port/api/explorer/v1/blocks?count=10 from different machines and both are successful. I got a block.

Blockchain and explorer are running on the same computer.

**Comment by vnermolaev** [comment]
Make sure that you have set up the exonum endpoint in the block-explorer to `http:// your-blockchain-host : port/api`.
You can do it in settings (the cogwheel icon).

**Comment by tipoc123** [comment]
Sorry, I don't understand. I've made "git clone https://github.com/nedap/exonum-block-explorer.git". Which file must I set up exonum endpoint in? Where is the cogwheel icon?

**Comment by vnermolaev** [comment]
I assume you get stuff working with `localhost:8080`.

Further, I've done some research for you: you need to configure webpack-dev-server.

https://webpack.js.org/guides/development/#using-webpack-dev-server
https://stackoverflow.com/questions/44423392/how-to-get-access-to-webpack-dev-server-with-external-ip

**Comment by tipoc123** [comment]
Now it's working but blocks are empty.
![screenshot from 2017-12-28 16-19-34](https://user-images.githubusercontent.com/15922591/34411960-4c9ac704-ebeb-11e7-93e5-0ee04695ceb9.png)

While API returns me a block info:
curl http:/x.x.x.x:8000/api/explorer/v1/blocks?count=10
[
  {
    "height": "0",
    "prev_hash": "0000000000000000000000000000000000000000000000000000000000000000",
    "proposer_id": 0,
    "schema_version": 0,
    "state_hash": "ad43a0c5a222e69a33919e393adc4ab98f8b2bf6acf179876ecb3bdef005b198",
    "tx_count": 0,
    "tx_hash": "0000000000000000000000000000000000000000000000000000000000000000"
  }
]

**Comment by tipoc123** [comment]
Now it's working but blocks are empty:
![blocks](https://user-images.githubusercontent.com/15922591/34419317-25119af4-ec14-11e7-89c6-72640690733d.png)

However API returns me a block info:
curl http:/x.x.x.x:8000/api/explorer/v1/blocks?count=10
[
{
"height": "0",
"prev_hash": "0000000000000000000000000000000000000000000000000000000000000000",
"proposer_id": 0,
"schema_version": 0,
"state_hash": "ad43a0c5a222e69a33919e393adc4ab98f8b2bf6acf179876ecb3bdef005b198",
"tx_count": 0,
"tx_hash": "0000000000000000000000000000000000000000000000000000000000000000"
}
]

**Comment by vnermolaev** [comment]
Actually in the Figure you attached first you can see that you did not enable the CORS changer.

Another thing. I would not recommend to allow access on the external ip, this explorer is not production ready in any way.

**Comment by tipoc123** [comment]
I have enabled CORS and changed Settings->Exonum explorer endpoint from localhost to my ip and it's working.

**Comment by tipoc123** [comment]
How to change "Exonum explorer endpoint" permanently?

**Comment by vnermolaev** [comment]
As is, it's not possible.

Your options are:
1. go into code, figure it out yourself or politely ask for guidance, make a pull request contributing back to the community.

2. submit a feature request and I will think about it.
